---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: goodbye
  namespace: lukas-zapletalovi-com-tenant
labels:
  appstudio.openshift.io/application: fedora-kickstart-artifacts
  appstudio.openshift.io/component: fedora-kickstart-artifacts
spec:
  params:
    - name: username
      type: string
  steps:
    - name: goodbye
      image: ubuntu
      script: |
        #!/bin/bash
        echo "Goodbye $(params.username)"
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: hello-goodbye
  namespace: lukas-zapletalovi-com-tenant
labels:
  appstudio.openshift.io/application: fedora-kickstart-artifacts
  appstudio.openshift.io/component: fedora-kickstart-artifacts
spec:
  workspaces:
    - name: ws
  params:
    - name: username
      type: string
  tasks:
    - name: hello
      taskRef:
        name: hello
      workspaces:
        - name: ws
          workspace: ws
    - name: goodbye
      runAfter:
        - hello
      taskRef:
        name: goodbye
      workspaces:
        - name: ws
          workspace: ws
      params:
        - name: username
          value: $(params.username)
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/lzap/fedora-kickstart-artifacts?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: fedora-kickstart-artifacts
    appstudio.openshift.io/component: fedora-kickstart-artifacts
    pipelines.appstudio.openshift.io/type: build
  name: fedora-kickstart-artifacts-on-pull-request
  namespace: lukas-zapletalovi-com-tenant
spec:
  pipelineRef:
    name: hello-goodbye
  workspaces:
  - name: ws
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
status: {}
